name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: get nix
        uses: cachix/install-nix-action@v30
      - name: update script
        run: |
          pkgs=$(nix flake show --json | jq -r '[.packages[] | keys[]] | sort | unique |  join(" ")')
          for pkg in $pkgs; do
            nix run github:Mic92/nix-update -- --flake --commit "$pkg" 1>/dev/null
          done
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          #limit-access-to-actor: true
          limit-access-to-users: AnasSaeed1
