name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: get nix
        uses: cachix/install-nix-action@v30
      - name: Run update script
        run: |
          for dir in ./*
            do cd $dir
            ./update.sh

