name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: get nix
        uses: cachix/install-nix-action@v30
      - name: git nobody
        run : |
          git config --global user.email "nobody"
          git config --global user.name "nix package updater"
      - name: update script
        run: |
          pkgs=$(nix flake show --json | jq -r '[.packages[] | keys[]] | sort | unique |  join(" ")')
          excludedPkgs=$(nix eval --json .#packages.nixUpdateExclude | jq -r '.| sort | unique |  join(",")')
          excludedPkgs=${excludedPkgs// /}
          excludedPkgs=${excludedPkgs//,/ }
          for pkg in $pkgs; do
            [[ ",$excludedPkgs," != *",$pkg,"* ]] && nix run github:Mic92/nix-update -- --flake --commit "$pkg" 1>/dev/null
          done
          git push
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          #limit-access-to-actor: true
          limit-access-to-users: AnasSaeed1
