name: nix-update
run-name: update pacakges
on: push
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: get nix
        uses: cachix/install-nix-action@v30
      - name: git nobody
        run : |
          git config --global user.email "nobody"
          git config --global user.name "nix package updater"
      - name: update script
        run: |
          nix build .#test
          ./result > packages.nix
          nix eval --expr "$(for i in $(nix eval .#packagesNoHash --apply builtins.attrNames|cut -b 3- |rev|cut -b 3- |rev); do nix eval --expr "{ $i = \"$(nix build .#packagesNoHash.$i.src 2>&1|grep got|rev | cut -d' ' -f 1-1 |rev)\";}" ; done | sed -z 's/\n/\/\//g' |rev | cut -b 3- |rev)" > hashes.nix
          git add packages.nix
          git add hashes.nix
          if [ -n "`git diff`" ]; then
            git commit -a -m "update hashes.nix packages.nix"
            git push
          fi
