name: nix-update
run-name: update pacakges
on: push
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: get nix
        uses: cachix/install-nix-action@v30
      - name: git nobody
        run : |
          git config --global user.email "nobody"
          git config --global user.name "nix package updater"
      - name: update script
        run: |
          nix eval --expr "$(for i in $(nix eval .#packagesNoHash --apply builtins.attrNames|cut -b 3- |rev|cut -b 3- |rev); do nix eval --expr "{ $i = \"$(nix build .#packagesNoHash.$i.src 2>&1|grep got|rev | cut -d' ' -f 1-1 |rev)\";}" ; done | sed -z 's/\n/\/\//g' |rev | cut -b 3- |rev)" > hashes.nix
          nix build .#test
          ./result > packages.nix
          (echo {; for i in `nix eval --impure --expr "builtins.attrNames(import ./packages.nix)" |cut -b 3- |rev|cut -b 3- |rev` ; do url=$(nix eval --impure --expr "(import ./packages.nix).$i.url"|cut -b2- |rev | cut -b2-| rev);i=$(echo $i|cut -b2-|rev|cut -b2-|rev); curl -Lso o "$url" ;echo \"$i\" = \[;for i in `patchelf --print-needed o`; do nix-locate -d files --minimal --top-level $i | grep \.out | head -n1 | xargs -I {} echo \"{}\";done;echo ]\;; done ; echo }) > deps.nix
          git add deps.nix
          git add packages.nix
          git add hashes.nix
          git commit -a -m "update hashes.nix packages.nix deps.nix"
          git push
